/*
=============================================================
Magnitude Analysis
=============================================================
Script Purpose:
    This script quantifies key business metrics across
    different dimensions in the chocolate sales dataset.

Steps Performed:
    1. Analyze product performance.
    2. Analyze country performance.
    3. Analyze sales channel performance.
    4. Analyze salesperson performance.
    
Metrics Analyzed:
    - Total orders
    - Total revenue
    - Total boxes shipped
    - Average discount percentage
    - Marketing spend    
*/


-- Analyze product performance.
-- Find total orders by product.
SELECT
    Product,
    COUNT(Order_ID) AS total_orders
FROM orders
GROUP BY Product
ORDER BY total_orders DESC;

-- Find total boxes shipped by product.
SELECT
    Product,
    SUM(Boxes_Shipped) AS total_boxes_shipped
FROM orders
GROUP BY Product
ORDER BY total_boxes_shipped DESC;

-- Find total revenue generated by each product.
SELECT
    Product,
    ROUND(SUM(Amount),2) AS total_revenue,
    ROUND(
        SUM(Amount) * 100.0 / SUM(SUM(Amount)) OVER(),
        2
    ) AS revenue_percentage
FROM orders
GROUP BY Product
ORDER BY total_revenue DESC;

-- Find average discount applied for each product.
SELECT
    Product,
    ROUND(AVG(Discount_Pct),2) AS average_discount
FROM orders
GROUP BY Product
ORDER BY average_discount DESC;


-- Analyze country performance.
-- Find total orders by country.
SELECT
    Country,
    COUNT(Order_ID) AS total_orders
FROM orders
GROUP BY Country
ORDER BY total_orders DESC;

-- Find total revenue generated by each country.
SELECT
    Country,
    ROUND(SUM(Amount),2) AS total_revenue,
    ROUND(
        SUM(Amount) * 100.0 / SUM(SUM(Amount)) OVER(),
        2
    ) AS revenue_percentage
FROM orders
GROUP BY Country
ORDER BY total_revenue DESC;


-- Find total boxes shipped by country.
SELECT
    Country,
    SUM(Boxes_Shipped) AS total_boxes_shipped
FROM orders
GROUP BY Country
ORDER BY total_boxes_shipped DESC;


-- Analyze sales channel performance.
-- Find total orders by sales channel.
SELECT
    Channel,
    COUNT(Order_ID) AS total_orders
FROM orders
GROUP BY Channel
ORDER BY total_orders DESC;


-- Find total revenue generated by each sales channel.
SELECT
    Channel,
    ROUND(SUM(Amount),2) AS total_revenue,
    ROUND(
        SUM(Amount) * 100.0 / SUM(SUM(Amount)) OVER(),
        2
    ) AS revenue_percentage
FROM orders
GROUP BY Channel
ORDER BY total_revenue DESC;


-- Find total boxes shipped by each sales channel.
SELECT
    Channel,
    SUM(Boxes_Shipped) AS total_boxes_shipped
FROM orders
GROUP BY Channel
ORDER BY total_boxes_shipped DESC;


-- Find marketing spend by sales channel.
SELECT
    Channel,
    ROUND(SUM(Marketing_Spend),2) AS total_marketing_spend
FROM orders
GROUP BY Channel
ORDER BY total_marketing_spend DESC;


-- Analyze salesperson performance.
-- Find total revenue generated by each salesperson.
SELECT
    Salesperson,
    ROUND(SUM(Amount),2) AS total_revenue,
    ROUND(
        SUM(Amount) * 100.0 / SUM(SUM(Amount)) OVER(),
        2
    ) AS revenue_percentage
FROM orders
GROUP BY Salesperson
ORDER BY total_revenue DESC;

-- Find total orders handled by each salesperson.
SELECT
    Salesperson,
    COUNT(Order_ID) AS total_orders
FROM orders
GROUP BY Salesperson
ORDER BY total_orders DESC;
